Proyecto Individual/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Individual/force-app/main/default/objects/Answer__c/fields/Is_correct__c.field-meta.xml
<CustomField>
    <fullName>Is_correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is correct?</label>
    <type>Checkbox</type>
</CustomField>

Proyecto Individual/force-app/main/default/objects/Answer__c/fields/User_Unit__c.field-meta.xml
<CustomField>
    <fullName>User_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User - Unit</label>
    <referenceTo>User_Unit__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Proyecto Individual/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Individual/force-app/main/default/objects/User_Answer__c/User_Answer__c.object-meta.xml
<CustomObject>
    <label>User - Answer</label>
    <nameField>
        <displayFormat>UA-{0000}</displayFormat>
        <label>User - Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proyecto Individual/force-app/main/default/objects/User_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>User - Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Proyecto Individual/force-app/main/default/objects/User_Answer__c/fields/User_Unit__c.field-meta.xml
<CustomField>
    <fullName>User_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User - Unit</label>
    <referenceTo>User_Unit__c</referenceTo>
    <relationshipLabel>User - Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Proyecto Individual/force-app/main/default/objects/User_Unit__c/User_Unit__c.object-meta.xml
<CustomObject>
    <label>User - Unit</label>
    <nameField>
        <displayFormat>UU-{0000}</displayFormat>
        <label>User - Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Individual/force-app/main/default/objects/User_Unit__c/fields/Numbers_Of_Tries__c.field-meta.xml
<CustomField>
    <fullName>Numbers_Of_Tries__c</fullName>
    <label>Numbers Of Tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Proyecto Individual/force-app/main/default/objects/User_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Proyecto Individual/force-app/main/default/objects/User_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>User - Units</relationshipLabel>
    <relationshipName>User_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

Proyecto Individual/force-app/main/default/classes/UnitResponses.cls
public class UnitResponses {

    public static void onBeforeUpdate(List<User_Unit__c>unitRespList,Map<Id,User_Unit__c>oldUnitRespMap){
        List<User_Unit__c> answeredUnitRespList = new List<User_Unit__c>();
        for(User_Unit__c unitResp:unitRespList){
            if(unitResp.Status__c == 'Answered' && oldUnitRespMap.get(unitResp.Id).Status__c == 'Draft'){
                answeredUnitRespList.add(unitResp);
            }
        }
        validateAnswers(answeredUnitRespList);
     
    }
    
     public static void onAfterUpdate(List<User_Unit__c>unitRespList,Map<Id,User_Unit__c>oldUnitRespMap){
        List<User_Unit__c> correctUnitRespList = new List<User_Unit__c>();
        for(User_Unit__c unitResp:unitRespList){
           if(unitResp.Status__c == 'Success'){
                correctUnitRespList.add(unitResp);
            }
        }
         updateUserPoints(correctUnitRespList);
    }
    
    private static void validateAnswers(List<User_Unit__c>unitRespList){
        Boolean verify = false;
        List<User_Unit__c> unitRespFromDb = [SELECT Id,Numbers_Of_Tries__c,Unit__r.Points__c,(SELECT Id,Answer__r.Is_correct__c FROM User_Answers__r) FROM User_Unit__c WHERE Id IN:unitRespList];
        Map<Id,User_Unit__c> unitRespFromDbMap = new Map<Id,User_Unit__c>(unitRespFromDb);
        
        for(User_Unit__c unitResp : unitRespList){
           
            for(User_Answer__c questionResp :unitRespFromDbMap.get(unitResp.id).User_Answers__r){
                unitResp.Status__c = 'Success';
               
                if(!questionResp.Answer__r.Is_correct__c){
                    unitResp.Status__c = 'Fail';
                    break;
                }
            }
            //Seteo de la unidad en la que estamos iterando
            if(unitResp.Status__c == 'Success'){
                if(unitResp.Numbers_Of_Tries__c == 1){
                    unitResp.Points__c = unitRespFromDbMap.get(unitResp.id).Unit__r.Points__c;
                }
                else if(unitResp.Numbers_Of_Tries__c == 2){
                    unitResp.Points__c = unitRespFromDbMap.get(unitResp.id).Unit__r.Points__c/2;
                }else{
                    unitResp.Points__c = unitRespFromDbMap.get(unitResp.id).Unit__r.Points__c/4;
                }
               
            }
        }
        
    }
    
    public static void updateUserPoints(List<User_Unit__c>unitRespList){
        //Seteo del los Ids de usuario por cada unidad respondida
        set<Id>usersIds =new set<Id>();
        for(User_Unit__c unitResp:unitRespList){
            usersIds.add(unitResp.User__c);
        }
        //Buscamos los usuarios asociados a las unidades respondidas en "User-Unit"
        Map<Id,User> usersMap = new Map<Id,User>([SELECT Id,Points__c FROM User WHERE Id in:usersIds]);
       
       //Actualizamos en memoria los puntos de cada usuario en base a las unidades respondidas:
        for(User_Unit__c unitResp: unitRespList){
            User user = usersMap.get(unitResp.User__c);
            user.Points__c = user.Points__c == Null ? unitResp.Points__c : user.Points__c + unitResp.Points__c; 
        }
        update usersMap.values();
    }
 }